fix(ClassOption): Return nil if value is not present
When the class option does not have a default value,
it fails with

    undefined method 'constantize' for nil (NoMethodError)

Returning `nil` instead gracefully handles the error.

Fixes an issue with the installer on a fresh Rails app,
because we do not have `Alchemy.config.user_class` default
but access it in `Alchemy::Engine`:150.

(cherry picked from commit 7ee2131e8383b4dcccd0a2c654ccd730681d52a8)